### ISSUE TITLE
bash: /media/imen/HDD/PFE/yolo/server: Is a directory

### ISSUE THREAD

**Issue by imenselmi** [ArgoHA/general_triton_yolo_pipeline#1]
i used this command to run triton but i got this error :  /media/imen/HDD/PFE/yolo/server --model-repository=/media/imen/HDD/PFE/yolo/general_triton_yolo_pipeline/model_repository/ --backend-directory=/media/imen/HDD/PFE/yolo/backends
bash: /media/imen/HDD/PFE/yolo/server: Is a directory

 i'm runing triton with docker container and without gpu , i used cpu only how can i run this command correctly

**Comment by ArgoHA** [comment]
Hi!
To start a triton server you need to use a binary like `bin/tritonserver` and then parameters like `--model-repository`
It's like when you want to run a python script you do `python` and then you add parameters like path to .py file

In my case tritonserver is installed in this directory `/home/argo/installation_triton/bin/tritonserver`
