### ISSUE TITLE
About the inference time

### ISSUE THREAD

**Issue by hongsamvo** [ArgoHA/general_triton_yolo_pipeline#3]
Thank you for your contribution. 
I read your issue https://github.com/triton-inference-server/server/issues/5229 and I don't know that did you figure out the problem.

**Comment by ArgoHA** [comment]
Hey @hongsamvo. I see better performance with more load (more video streams in parallel). For 1 stream and 1 model triton is not the best choice if latency is crucial.
As I understand: It takes time to pass a tensor via gRPC to the triton for model's forward pass. It is faster to load model to vRAM and directly call it. But you can't do that if you have many clients.
Also I did test preprocessing and post processing a lot, changing only inference type and I definitely see that the slowdown is when I pass image to triton.

So please test if this is a good fit for your use case.

**Comment by hongsamvo** [comment]
@ArgoHA Thank you for your recommendation. My app focus on serving multiple video stream, I will test more to find that if triton good fit for my app.

**Comment by hongsamvo** [comment]
Hi, I just test my service, it cost about 30ms for send image and receive output using triton, while yolo only cost 15ms(pytorch).

**Comment by ArgoHA** [comment]
I think you also might infer with cut paddings of letterbox in yolo (by default), so img size is not 640x640, but like 640x480 or any other value dividable by 32. So torch model actually does less compute, that's why you see such a big difference. 

And grpc serializing-deserializing also gives you an overhead, as I wrote in above.

**Comment by hongsamvo** [comment]
Thank you for your recommendation. I expected grpc will much more faster compare to my current solution zmq
